import 'constants.dart';

const String kPackagePath = "$kIconPath/package_type";

Map<String, String> kStatus = {
  "1": "Find Driver",
  "2": "Driver Found",
  "3": "Process",
  "4": "Complete",
  "5": "Cancel",
};

Map<int, dynamic> kCategories = {
  1: {"icon": "bike", "label": "Bike", "path": "/bike"},
  2: {"icon": "food", "label": "Food", "path": "/bike"},
  3: {"icon": "send-goods", "label": "Send Goods", "path": "/bike"},
  4: {"icon": "shopping", "label": "Shopping", "path": "/bike"},
  5: {"icon": "truck", "label": "Truck", "path": "/bike"},
  6: {"icon": "medicine", "label": "Medicines", "path": "/bike"},
  7: {"icon": "grocery", "label": "Grocery", "path": "/bike"},
};

List<String> indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

final List<String> returnReasons = [
  "Damaged or Defective Item",
  "Received Wrong Product",
  "Item Not as Described",
  "Size/Dimension Mismatch",
  "Quality Not as Expected",
  "Received an Incomplete Product",
  "Product Has Manufacturing Defects",
  "Color or Design Variation Issue",
  "Item is Broken or Cracked",
  "Material Feels Different Than Expected",
  "Product Has a Strong Odor",
  "Excessive Wear and Tear on Arrival",
  "Item Warped or Misshapen",
  "Mold or Fungus Growth on Item",
  "Item Feels Weak or Not Sturdy",
  "Product Not Suitable for Intended Use",
  "Delayed Delivery, No Longer Needed",
  "Better Alternative Found Elsewhere",
  "Duplicate Order Placed by Mistake",
  "Gift Purchase Not Suitable for Recipient",
  "Item Causing Allergic Reaction",
  "Packaging Was Open or Tampered",
  "Received an Expired or Old Stock",
  "Product is Too Heavy/Light Than Expected",
  "Personal Preference Change",
  "Accidental Purchase",
];

final List<Map<String, String>> countries = [
  {"name": "United States", "code": "+1", "emoji": "🇺🇸"},
  {"name": "Canada", "code": "+1", "emoji": "🇨🇦"},
  {"name": "United Kingdom", "code": "+44", "emoji": "🇬🇧"},
  {"name": "India", "code": "+91", "emoji": "🇮🇳"},
  {"name": "Germany", "code": "+49", "emoji": "🇩🇪"},
  {"name": "France", "code": "+33", "emoji": "🇫🇷"},
  {"name": "Italy", "code": "+39", "emoji": "🇮🇹"},
  {"name": "Australia", "code": "+61", "emoji": "🇦🇺"},
  {"name": "Brazil", "code": "+55", "emoji": "🇧🇷"},
  {"name": "Japan", "code": "+81", "emoji": "🇯🇵"},
  {"name": "South Korea", "code": "+82", "emoji": "🇰🇷"},
  {"name": "China", "code": "+86", "emoji": "🇨🇳"},
  {"name": "Mexico", "code": "+52", "emoji": "🇲🇽"},
  {"name": "Russia", "code": "+7", "emoji": "🇷🇺"},
  {"name": "South Africa", "code": "+27", "emoji": "🇿🇦"},
  {"name": "Spain", "code": "+34", "emoji": "🇪🇸"},
  {"name": "Netherlands", "code": "+31", "emoji": "🇳🇱"},
  {"name": "Sweden", "code": "+46", "emoji": "🇸🇪"},
  {"name": "Norway", "code": "+47", "emoji": "🇳🇴"},
  {"name": "Switzerland", "code": "+41", "emoji": "🇨🇭"},
  {"name": "New Zealand", "code": "+64", "emoji": "🇳🇿"},
  {"name": "Turkey", "code": "+90", "emoji": "🇹🇷"},
  {"name": "Argentina", "code": "+54", "emoji": "🇦🇷"},
  {"name": "Indonesia", "code": "+62", "emoji": "🇮🇩"},
  {"name": "Saudi Arabia", "code": "+966", "emoji": "🇸🇦"},
  {"name": "United Arab Emirates", "code": "+971", "emoji": "🇦🇪"},
  {"name": "Nepal", "code": "+977", "emoji": "🇳🇵"},
];
