// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcpX9t5Ton_a6ZL6_fxea-ArGd6xiNaw',
    appId: '1:1054776721386:android:3044a4ced4fad3cea77c93',
    messagingSenderId: '1054776721386',
    projectId: 'hello-captain-2cec6',
    databaseURL: 'https://hello-captain-2cec6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hello-captain-2cec6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx20jLMjY6DJAIppxIbQ5W1mVXyc-857E',
    appId: '1:1054776721386:ios:80ab645b76fab31fa77c93',
    messagingSenderId: '1054776721386',
    projectId: 'hello-captain-2cec6',
    databaseURL: 'https://hello-captain-2cec6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hello-captain-2cec6.firebasestorage.app',
    iosBundleId: 'com.example.helloCaptainUser',
  );
}
